### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sasforce** [gtoubassi/TensorFlowOnAWSwithGPU#2]
Dear Gtoubassi
Thank you for your code and I find that something puzzles me.
The running step4, what is the game ROM, and how to download it?
Thank you for your reply.
Yours Luo

**Comment by gtoubassi** [comment]
Hi Luo!  The ROM is essentially the software image of the cartridge for the Atari game you are training on.  The emulator does not itself have any roms.  So you need to download a file for each game.  You should be able to google them and find them on various (often sketchy looking) sites.
